name: Training Workflow

on:
  workflow_call:
    inputs:
        environment:
            description: 'Environment for the training job'
            required: true
            type: string
        python-version:
            description: 'Python version'
            required: false
            default: '3.11'
            type: string
        tune_hyperparameters:
            description: 'Enable hyperparameter tuning'
            required: false
            default: true
            type: boolean
    
    secrets:
      DO_SPACES_ACCESS_KEY:
        required: true
      DO_SPACES_SECRET_KEY:
        required: true
      DO_SPACES_BUCKET:
        required: true
      DO_SPACES_REGION:
        required: true

jobs:
  training:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: Run training script
        run: |
          source .venv/bin/activate
          if [ "${{ inputs.tune_hyperparameters }}" == "true" ]; then
            uv run tools/run.py --run-train --tune
          else
            uv run tools/run.py --run-train
          fi

      - name: Upload trained model to DigitalOcean Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACES_BUCKET }}
          space_region: ${{ secrets.DO_SPACES_REGION }}
          source: models/
          out_dir: models/${{ github.run_number }}-${{ github.sha }}
